[project]
name = "vand2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.0.0",
    "pillow>=10.0.0",
    "scikit-learn>=1.5.0",
    "tifffile>=2024.8.30",
    "torch==2.4.1+cu124",
    "torchvision==0.19.1+cu124",
    "tqdm>=4.67.3",
]

[tool.uv]
find-links = [
    "https://download.pytorch.org/whl/cu124/torch",
    "https://download.pytorch.org/whl/cu124/torchvision",
]
